-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 20:26:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PerManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PerManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PerManagement` DEFAULT CHARACTER SET utf8 ;
USE `PerManagement` ;

-- -----------------------------------------------------
-- Table `PerManagement`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PerManagement`.`Department` (
  `idDepartment` CHAR(3) NOT NULL,
  `DepartmentName` VARCHAR(45) NULL,
  `DepartmentComment` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PerManagement`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PerManagement`.`Person` (
  `idPerson` CHAR(8) NOT NULL,
  `PersonPho` MEDIUMTEXT NULL,
  `PersonName` VARCHAR(30) NULL,
  `PersonBirthDate` DATE NULL,
  `PersonNation` VARCHAR(5) NULL,
  `PersonPoliticalOutlook` VARCHAR(6) NULL,
  `PersonIsMarry` TINYINT NULL,
  `PersonTitle` VARCHAR(10) NULL,
  `PersoncolMajor` VARCHAR(10) NULL,
  `PersonEducation` ENUM('本科', '专科', '硕士', '博士') NULL,
  `PersonGraduationSchool` VARCHAR(10) NULL,
  `PersonGraduationDate` DATE NULL,
  `PersonBaseSalary` DECIMAL NULL,
  `PersonIDNumber` VARCHAR(18) NULL,
  `PersonDepartementNum` VARCHAR(3) NULL,
  `PersonWorkPosition` VARCHAR(10) NULL,
  `PersonTeam` VARCHAR(10) NULL,
  `PersonAdmissionDate` DATE NULL,
  `PersonParticipateDate` DATE NULL,
  `PersonCategory` ENUM('工人', '干部', '临时工') NULL,
  `PersoncolContractPeriod` INT NULL,
  `PersonFamilyAddress` VARCHAR(45) NULL,
  `PersonContactInformation` VARCHAR(11) NULL,
  `PersonComment` VARCHAR(45) NULL,
  `PersonGender` ENUM('男', '女') NULL,
  `PersonState` ENUM('在职', '离退') NULL,
  PRIMARY KEY (`idPerson`),
  INDEX `departmentNumber_idx` (`PersonDepartementNum` ASC),
  CONSTRAINT `departmentNumber`
    FOREIGN KEY (`PersonDepartementNum`)
    REFERENCES `PerManagement`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PerManagement`.`Salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PerManagement`.`Salary` (
  `idSalary` INT NOT NULL AUTO_INCREMENT,
  `SalaryCardNumber` VARCHAR(20) NULL,
  `SalaryidPerson` CHAR(8) NULL,
  `SalaryBase` DECIMAL NULL,
  `SalaryWorkYears` INT NULL,
  `SalaryWorkYearsAllowance` DECIMAL NULL,
  `SalaryFoodSubsidy` DECIMAL NULL,
  `SalaryMan-hourCompletionRate` VARCHAR(5) NULL DEFAULT '0%',
  `SalaryQualityVetoCoefficient` VARCHAR(5) NULL DEFAULT '0%',
  `SalaryAttendanceDays` INT NULL DEFAULT 0,
  `SalaryBasicPay` DECIMAL NULL,
  `SalarycolWorkSubsidy` DECIMAL NULL,
  `SalaryHouseSubsidy` DECIMAL NULL,
  `SalaryHealthFee` DECIMAL NULL,
  `SalaryNightSnackFee` DECIMAL NULL,
  `SalaryOvertimeFee` DECIMAL NULL,
  `SalaryMaternityLeave` INT NULL,
  `SalaryFlexibleSubsidy` DECIMAL NULL,
  `SalaryFlexibleDeduction` DECIMAL NULL,
  `SalaryTeamSubsidy` DECIMAL NULL,
  `SalaryPayable` DECIMAL NULL,
  `SalaryInsuranceMoney` DECIMAL NULL,
  `SalaryPayFund` DECIMAL NULL,
  `SalaryIncomeTax` DECIMAL NULL,
  `SalaryDeduction` DECIMAL NULL,
  `SalaryHouseFee` DECIMAL NULL,
  `SalarWaterFee` DECIMAL NULL,
  `SalaryElectricityFee` DECIMAL NULL,
  `SalaryReal` DECIMAL NULL,
  `SalaryComment` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalary`),
  INDEX `idPerson_idx` (`SalaryidPerson` ASC),
  CONSTRAINT `idPerson`
    FOREIGN KEY (`SalaryidPerson`)
    REFERENCES `PerManagement`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
